// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhlcmfxrrspnovgkuvya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpobGNtZnhycnNwbm92Z2t1dnlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyODU4NzMsImV4cCI6MjA3Mjg2MTg3M30.4CKSwP5kRtarGGYECQuGYKNFwfq0w5BwvQeyq1U-7UQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});